add initial table creates to sql init
ukraineunited/ukrainewillstand pull request #11
Opened 2022-02-26 22:39 UTC by morganjcw

2022-02-26 22:42 UTC, morganjcw commented
Need a maintainer to approve running workflows but @strikefvela @helloimalastair tagging you here

2022-02-27 07:34 UTC, skrtu commented on backend/db_init.sql
> +CREATE TABLE IF NOT EXISTS users(
can we remove the user table? we should just use the `user_id` field from Auth0 to reference other objects I think.

2022-02-27 07:34 UTC, skrtu commented on backend/db_init.sql
> +CREATE TABLE IF NOT EXISTS notifications (
can we add a `user_id` here?

2022-02-27 07:36 UTC, skrtu requested changes
Hey if you could review my comments before we merge.

2022-02-28 06:52 UTC, skrtu approved these changes
LGTM 👍

2022-02-28 13:48 UTC, morganjcw commented
@skrtu can I get another review on this?

2022-02-28 20:44 UTC, merged